apiVersion: v1
kind: Deployment
metadata:
  name: MyWebApp
spec:
  selector:
    matchLabels:
      app: MyWebApp
  template:
    metadata:
      labels:
        app: MyWebAppp
    spec:
      containers:
      - name: MyWebApp
        image: cft:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
